name: CMake

on:
  push:
    branches: [ master ]
    tags: -"v*1.*"

env:
  
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    

    - name: Build
      # Build your program with the given configuration
      run: |
        touch time.txt
        /bin/time -po time.txt sh -c '
        cmake -H. -B_build -DCPACK_GENERATOR="TGZ";
        cmake --build _build --target package
        ' 
        cd _build
        cpack -G "DEB"
      
        mkdir ../artifacts
        mv *.deb ../artifacts/
   
   
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts/
